set shell=/bin/zsh

"" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'crusoexia/vim-monokai'
Plug 'ConradIrwin/vim-bracketed-paste'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/syntastic'
" Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
" Plug 'Valloric/YouCompleteMe', Cond(has('cmake'), { 'do': './install.py' })
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
" Plug 'Yggdroot/indentLine'
call plug#end()

" Aux Functions
function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

"" User interface
syntax enable
colorscheme monokai
" set term=screen-256color
set showmatch               " Show matching braces when over one
set ruler                   " Always show current position
set antialias               " Pretty fonts
set number                  " Always show line-numbers
set numberwidth=5           " Line-number margin width
set display=lastline        " Show as much as possible of the last line.
set laststatus=2            " Always show the status bar
set ttyfast                 " Faster redrawing.
set lazyredraw              " Only redraw when necessary.
set cursorline              " Find the current line quickly.
set wrapscan                " Searches wrap around end-of-file.
set report=0                " Always report changed lines.
" set list                    " Show non-printable characters.
set title
" set list listchars=tab:▷⋅,trail:⋅,nbsp:⋅
" set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\
" \ [%l/%L\ (%p%%)
filetype plugin indent on

"" General edition config
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab
set backspace=indent,eol,start     " Make backspace work as you would expect.
set incsearch
au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=79 " PEP-8 Friendly2

"" General behaviour
set autochdir               " CWD is always same as current file
set ai                      " Autoindent
set nocompatible            " ViM settings instead of Vi

"" Plugins config
let g:NERDSpaceDelims = 1   " Add spaces after comment delimiters by default
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:indentLine_color_term = 239

"" Key mappings
" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
map \\ :NERDTreeToggle<CR>
" Mappings to move lines (http://vim.wikia.com/wiki/Moving_lines_up_or_down)
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
