"" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'nanotech/jellybeans.vim'
Plug 'crusoexia/vim-monokai'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/syntastic'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'lervag/vimtex'
call plug#end()

" Aux Functions
function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

"" User interface
syntax enable
colorscheme monokai
set showmatch                   " Show matching braces when over one
set ruler                       " Always show current position
set antialias                   " Pretty fonts
set number                      " Always show line-numbers
set numberwidth =5              " Line-number margin width
set display     =lastline       " Show as much as possible of the last line.
set laststatus  =2              " Always show the status bar
set ttyfast                     " Faster redrawing.
set lazyredraw                  " Only redraw when necessary.
set cursorline                  " Find the current line quickly.
set wrapscan                    " Searches wrap around end-of-file.
set breakindent
set report      =0              " Always report changed lines.
" set list                      " Show non-printable characters.
set title
set t_ut        =               " TMUX Display http://superuser.com/questions/399296/256-color-support-for-vim-background-in-tmux

filetype plugin indent on

"" General edition config
set tabstop     =4 
set softtabstop =4 
set shiftwidth  =4 
set expandtab 
set smarttab
set backspace   =indent,eol,start   " Make backspace work as you would expect.
set incsearch                       " Highlight while searching with / or ?.

au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth =79   " PEP-8 Friendly2

"" General behaviour
set autochdir                       " CWD is always same as current file
set ai                              " Autoindent
set nocompatible                    " ViM settings instead of Vi
set mouse       =a

"" Plugins config
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes':   [],'passive_filetypes': ['tex'] }
let g:vimtex_quickfix_ignored_warnings = ['Underfull', 'Overfull', 'specifier changed to']

"" Key mappings
" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
map \\ :NERDTreeToggle<CR>
" Mappings to move lines (http://vim.wikia.com/wiki/Moving_lines_up_or_down)
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
" VimTeX mappings
nmap <F5> <plug>(vimtex-compile-toggle)

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#handling-backup-swap-undo-and-viminfo-files
if exists('*mkdir') && !isdirectory($HOME.'/.vim/ml_files')
  call mkdir($HOME.'/.vim/ml_files')
  call mkdir($HOME.'/.vim/ml_files/backup')
  call mkdir($HOME.'/.vim/ml_files/swap')
  call mkdir($HOME.'/.vim/ml_files/undo')
  call mkdir($HOME.'/.vim/ml_files/info')
endif
set backup
set backupdir   =$HOME/.vim/ml_files/backup/
set backupext   =-vimbackup
set backupskip  =
set directory   =$HOME/.vim/ml_files/swap//
set updatecount =100
set undofile
set undodir     =$HOME/.vim/ml_files/undo/
set viminfo     ='100,n$HOME/.vim/ml_files/info/viminfo
