export TERM="xterm-256color"
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions)

# User configuration
export HOSTALIASES=~/.hosts
# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
#if [[ -n $SSH_CONNECTION ]]; then
#  export EDITOR='vim'
# else
#  export EDITOR='gvim'
#fi

# Always use vim
export EDITOR='vim'


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias zshreload="source ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias autossh='autossh -M $(($RANDOM%6400 + 1024))' 
# alias pipenv='source ~/venv/bin/activate'
alias kzus="kubectl --context='zooba-cilium-prod.us-east-1.k8s.tfgco.com'"

# Custom Functions

# Head gzipped files with arguments
zhead() { 
    zcat ${@: -1} | head ${@:1:$(($#-1))};
}

# Print a comma thousands separator
thousandmark() {
    sed -E ':a;s/([0-9])([0-9]{3}([^0-9]|$))/\1,\2/g;ta'
}

# Print the header and certain lines of the file side-by-side
multiresume() {
    rm -f /tmp/multiresume*
    file="${@:$#}"
    for row in 1 "${@:1:$#-1}"; do
        zhead -n $row $file | tail -n 1 | tr '|' '\n' > /tmp/multiresume$row;
    done;

    paste /tmp/multiresume* | cat -n | column -s"$(echo -ne '\t')" -t
}

# Count value appearances in a column
valcount() {
    sort $1 | uniq -c
}

# Send mail with process status
mailme() {
    mail -s "Process $! finished with status $?" $1 < /dev/null
}

smux() {
    if [ "X$1" = "X" ]; then
        echo "usage: `basename $0` <host>"
    fi

    if [ "X$SSH_AUTH_SOCK" = "X" ]; then
            eval `ssh-agent -s`
            ssh-add $HOME/.ssh/id_rsa
    fi

    AUTOSSH_POLL=20
    AUTOSSH_PORT=$(awk 'BEGIN { srand(); do r = rand()*32000; while ( r < 20000 ); printf("%d\n",r)  }' < /dev/null)
    #AUTOSSH_GATETIME=30
    #AUTOSSH_LOGFILE=$HOST.log
    AUTOSSH_DEBUG=yes
    #AUTOSSH_PATH=/usr/local/bin/ssh
    export AUTOSSH_POLL AUTOSSH_LOGFILE AUTOSSH_DEBUG AUTOSSH_PATH AUTOSSH_GATETIME AUTOSSH_PORT
    # -t is the ssh option to force a pseudo terminal (pty)
    echo $@
    autossh -t $@ "tmux -A new-session"
}
